import { useState } from 'react';
import { DollarSign, Activity, BarChart3, Download, ArrowUpRight, ArrowDownRight, Clock } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useSystemEngine } from '../../../context/SystemEngineContext';

type Period = 'Daily' | 'Weekly' | 'Monthly';

export default function FinanceDashboard() {
  const [period, setPeriod] = useState<Period>('Monthly');
  const { revenue, expenses, transactions, financeChartData } = useSystemEngine();

  const handlePeriodChange = (p: Period) => {
    setPeriod(p);
    // Simulate fetching new data
    // In a real app, this would fetch from backend. We just keep the UI functional.
  };

  const formatCurrency = (val: number) => {
    if (val >= 1000000) return `$${(val / 1000000).toFixed(2)}M`;
    if (val >= 1000) return `$${(val / 1000).toFixed(1)}K`;
    return `$${val.toFixed(2)}`;
  };

  return (
    <div className="space-y-6 pb-10">
      {/* HEADER */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 bg-white/60 backdrop-blur-md rounded-[32px] p-6 shadow-sm border border-white">
        <div>
          <h2 className="text-2xl font-bold text-slate-800">Financial Overview</h2>
          <p className="text-sm text-slate-500 font-medium">Real-time financial metrics generated by AI Engine.</p>
        </div>
        
        <div className="flex items-center gap-3">
          <div className="bg-slate-100 p-1 rounded-xl flex items-center">
            {(['Daily', 'Weekly', 'Monthly'] as Period[]).map((p) => (
              <button
                key={p}
                onClick={() => handlePeriodChange(p)}
                className={`px-4 py-2 rounded-lg text-sm font-bold transition-all ${period === p ? 'bg-white text-emerald-600 shadow-sm' : 'text-slate-500 hover:text-slate-800'}`}
              >
                {p}
              </button>
            ))}
          </div>
          <button className="hidden sm:flex items-center gap-2 px-5 py-2.5 bg-emerald-600 hover:bg-emerald-700 transition-colors text-white text-sm font-bold rounded-xl shadow-lg shadow-emerald-500/20">
            <Download size={16} /> Export
          </button>
        </div>
      </div>

      {/* STATS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        {[
          { title: 'Total Revenue', value: formatCurrency(revenue), icon: DollarSign, color: 'text-emerald-500', bg: 'bg-emerald-50', trend: '+14.5%', isUp: true },
          { title: 'Total Expenses', value: formatCurrency(expenses), icon: Activity, color: 'text-rose-500', bg: 'bg-rose-50', trend: '-2.4%', isUp: false },
          { title: 'Net Margin', value: `${((1 - expenses/revenue) * 100).toFixed(1)}%`, icon: BarChart3, color: 'text-blue-500', bg: 'bg-blue-50', trend: '+5.2%', isUp: true },
        ].map((stat, i) => (
          <motion.div 
            key={i}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: i * 0.1 }}
            className="bg-white rounded-[32px] p-6 md:p-8 shadow-sm border border-slate-100 relative overflow-hidden group"
          >
            <div className={`absolute -right-6 -top-6 w-24 h-24 rounded-full ${stat.bg} blur-2xl group-hover:scale-150 transition-transform duration-700 opacity-50`} />
            
            <div className="flex items-center justify-between mb-8 relative z-10">
              <div className={`p-3 rounded-2xl ${stat.bg} ${stat.color}`}>
                <stat.icon className="w-6 h-6" strokeWidth={2.5} />
              </div>
              <div className={`flex items-center gap-1 text-xs font-bold px-2.5 py-1 rounded-full ${stat.isUp ? 'bg-emerald-50 text-emerald-600' : 'bg-rose-50 text-rose-600'}`}>
                {stat.isUp ? <ArrowUpRight size={14} /> : <ArrowDownRight size={14} />} {stat.trend}
              </div>
            </div>
            
            <div className="relative z-10">
              <h3 className="text-slate-400 font-bold text-sm tracking-wide uppercase mb-1">{stat.title}</h3>
              <motion.div 
                key={stat.value}
                initial={{ scale: 0.9, opacity: 0 }}
                animate={{ scale: 1, opacity: 1 }}
                className="text-4xl font-black text-slate-800 tracking-tight"
              >
                {stat.value}
              </motion.div>
            </div>
          </motion.div>
        ))}
      </div>

      {/* CHART & TRANSACTIONS */}
      <div className="grid grid-cols-1 xl:grid-cols-3 gap-6">
        
        {/* Main Chart */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
          className="xl:col-span-2 bg-white rounded-[32px] p-8 shadow-sm border border-slate-100 flex flex-col"
        >
          <div className="flex items-center justify-between mb-8">
            <div>
              <h3 className="font-bold text-lg text-slate-800">Cashflow Analytics</h3>
              <p className="text-sm text-slate-500">Real-time revenue projection vs actual</p>
            </div>
            <div className="flex items-center gap-4 text-sm font-bold">
              <div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full bg-emerald-500" /> Revenue</div>
              <div className="flex items-center gap-2"><span className="w-3 h-3 rounded-full bg-slate-200" /> Target</div>
            </div>
          </div>

          <div className="flex-1 flex items-end justify-between gap-2 sm:gap-6 pt-10 relative">
            {/* Grid lines */}
            <div className="absolute inset-0 flex flex-col justify-between pointer-events-none pb-8 opacity-40">
              {[0, 1, 2, 3].map((i) => (
                <div key={i} className="w-full border-b border-dashed border-slate-300 flex-1" />
              ))}
            </div>

            {/* Bars */}
            {financeChartData.map((h, i) => {
              const labels = period === 'Daily' ? ['9AM', '11AM', '1PM', '3PM', '5PM', 'NOW'] 
                           : period === 'Weekly' ? ['MON', 'TUE', 'WED', 'THU', 'FRI', 'SAT'] 
                           : ['JAN', 'FEB', 'MAR', 'APR', 'MAY', 'JUN'];
              
              const isLatest = i === financeChartData.length - 1;

              return (
                <div key={i} className="relative z-10 flex flex-col items-center gap-4 w-full group h-full justify-end">
                  {/* Tooltip */}
                  <div className="absolute -top-10 opacity-0 group-hover:opacity-100 transition-opacity bg-slate-800 text-white text-xs font-bold px-3 py-1.5 rounded-lg shadow-xl whitespace-nowrap pointer-events-none">
                    ${(h * 24000).toLocaleString()}
                  </div>

                  <div className="relative w-full max-w-[48px] h-[200px] sm:h-[260px] flex items-end bg-slate-50 rounded-2xl overflow-hidden shadow-inner">
                    {/* Background Target Bar */}
                    <div className="absolute bottom-0 w-full bg-slate-200 rounded-2xl" style={{ height: `${Math.min(100, h + 15)}%` }} />
                    {/* Actual Revenue Bar */}
                    <motion.div 
                      layout
                      initial={{ height: 0 }}
                      animate={{ height: `${h}%` }}
                      transition={{ type: "spring", stiffness: 100, damping: 15 }}
                      className={`absolute bottom-0 w-full rounded-2xl ${isLatest ? 'bg-gradient-to-t from-emerald-600 to-emerald-400 shadow-[0_0_20px_rgba(52,211,153,0.4)]' : 'bg-emerald-500'}`}
                    />
                  </div>
                  <span className={`text-[11px] font-bold ${isLatest ? 'text-emerald-600' : 'text-slate-400'}`}>{labels[i]}</span>
                </div>
              );
            })}
          </div>
        </motion.div>

        {/* Live Transactions */}
        <motion.div 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.4 }}
          className="xl:col-span-1 bg-white rounded-[32px] p-8 shadow-sm border border-slate-100 flex flex-col h-full min-h-[400px]"
        >
          <div className="flex items-center justify-between mb-6">
            <h3 className="font-bold text-lg text-slate-800">Live Ledger</h3>
            <div className="flex items-center gap-1 text-xs font-bold text-emerald-500 bg-emerald-50 px-2.5 py-1 rounded-full">
              <div className="w-1.5 h-1.5 rounded-full bg-emerald-500 animate-pulse" /> Syncing
            </div>
          </div>

          <div className="flex-1 overflow-hidden relative">
            <div className="absolute inset-x-0 top-0 h-4 bg-gradient-to-b from-white to-transparent z-10 pointer-events-none" />
            <div className="absolute inset-x-0 bottom-0 h-8 bg-gradient-to-t from-white to-transparent z-10 pointer-events-none" />
            
            <div className="space-y-4 pt-2">
              <AnimatePresence initial={false}>
                {transactions.map((tx) => (
                  <motion.div 
                    key={tx.id}
                    initial={{ opacity: 0, height: 0, y: -20 }}
                    animate={{ opacity: 1, height: 'auto', y: 0 }}
                    exit={{ opacity: 0, height: 0 }}
                    transition={{ type: "spring", stiffness: 300, damping: 25 }}
                    className="flex items-center justify-between p-4 rounded-2xl bg-slate-50/80 border border-slate-100/50 hover:bg-slate-100 transition-colors cursor-default"
                  >
                    <div className="flex items-center gap-3">
                      <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${tx.isPositive ? 'bg-emerald-100 text-emerald-600' : 'bg-rose-100 text-rose-600'}`}>
                        {tx.isPositive ? <ArrowDownRight size={18} strokeWidth={2.5} /> : <ArrowUpRight size={18} strokeWidth={2.5} />}
                      </div>
                      <div>
                        <div className="font-bold text-sm text-slate-800 line-clamp-1">{tx.type}</div>
                        <div className="flex items-center gap-1 text-[11px] font-medium text-slate-400 mt-0.5">
                          <Clock size={10} /> {tx.time}
                        </div>
                      </div>
                    </div>
                    <div className={`font-bold text-sm ${tx.isPositive ? 'text-emerald-600' : 'text-slate-800'}`}>
                      {tx.isPositive ? '+' : '-'}${tx.amount.toLocaleString(undefined, {minimumFractionDigits: 2})}
                    </div>
                  </motion.div>
                ))}
              </AnimatePresence>
            </div>
          </div>
          
          <button className="w-full mt-6 py-3.5 bg-slate-50 hover:bg-slate-100 text-slate-600 font-bold text-sm rounded-xl transition-colors">
            View Complete Ledger
          </button>
        </motion.div>

      </div>
    </div>
  );
}
