import { DollarSign, Activity, BarChart3 } from 'lucide-react';
import { motion } from 'framer-motion';

export default function FinanceDashboard() {
  return (
    <div className="space-y-6">
      <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100 mb-8">
        <h2 className="text-xl font-bold text-slate-800 mb-2">Financial Overview</h2>
        <p className="text-sm text-slate-500">Real-time financial metrics and analytics generated by AI Finance.</p>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-slate-500 font-medium text-sm">Total Revenue</h3>
            <div className="p-2 bg-slate-50 rounded-lg"><DollarSign className="w-5 h-5 text-emerald-500" /></div>
          </div>
          <div className="text-3xl font-bold text-slate-800">$2.4M</div>
        </div>
        <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-slate-500 font-medium text-sm">Expenses</h3>
            <div className="p-2 bg-slate-50 rounded-lg"><Activity className="w-5 h-5 text-red-500" /></div>
          </div>
          <div className="text-3xl font-bold text-slate-800">$840K</div>
        </div>
        <div className="bg-white rounded-3xl p-6 shadow-sm border border-slate-100">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-slate-500 font-medium text-sm">Growth (MoM)</h3>
            <div className="p-2 bg-slate-50 rounded-lg"><BarChart3 className="w-5 h-5 text-blue-500" /></div>
          </div>
          <div className="text-3xl font-bold text-slate-800">+14.5%</div>
        </div>
      </div>

      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.5 }}
        className="mt-8 bg-white p-6 rounded-3xl border border-slate-100 shadow-sm"
      >
        <h3 className="font-bold text-slate-800 mb-4">Recent Transactions</h3>
        <div className="space-y-3">
          {[1, 2, 3].map((i) => (
            <div key={i} className="flex items-center justify-between p-4 rounded-2xl bg-slate-50">
              <div className="flex items-center gap-3">
                <div className="w-10 h-10 rounded-xl bg-emerald-100 flex items-center justify-center text-emerald-600">
                  <DollarSign size={18} />
                </div>
                <div>
                  <div className="font-medium text-slate-700">Incoming Transfer</div>
                  <div className="text-xs text-slate-400">Today, 10:42 AM</div>
                </div>
              </div>
              <div className="font-bold text-emerald-600">+$12,450.00</div>
            </div>
          ))}
        </div>
      </motion.div>
    </div>
  );
}
